spring:

  application:
    name: stock

  kafka:
    consumer:
      group-id: stock-${random.uuid}
      auto-offset-reset: earliest
      #bootstrap-servers: flexIT.ruv.de
     #producer:
       #bootstrap-servers: flexIT.ruv.de

server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

